import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import { Video } from "../types";
import { VideoCard, NoResults } from "../components";
import { BASE_URL } from "../utils";

interface Iprops {
  videos: Video[];
}

const Home: NextPage<Iprops> = ({ videos }) => {
  return (
    <>
      <Head>
        <title>4go</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-10 videos h-full">
        {videos.length ? (
          videos?.map((video: Video) => (
            <VideoCard post={video} isShowingOnHome key={video._id} />
          ))
        ) : (
          <NoResults text={`No Videos`} />
        )}
      </div>
    </>
  );
};

export const getServerSideProps = async ({
  query: { topic },
}: {
  query: { topic: string };
}) => {
  let response = await axios.get(`${BASE_URL}/api/post`);

  if (topic) {
    response = await axios.get(`${BASE_URL}/api/discover/${topic}`);
  }

  await console.log(response.data);
  return {
    props: { videos: response.data },
  };
};

export default Home;
